//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeaconDevice()
        {
            this.User2 = new HashSet<User2>();
            this.Infos = new HashSet<Infos>();
        }
    
        public string d_id { get; set; }
        public string d_name { get; set; }
        public System.DateTime d_out_day { get; set; }
        public string d_location1 { get; set; }
        public string d_location2 { get; set; }
        public string d_location3 { get; set; }
        public string d_location4 { get; set; }
        public string d_holder { get; set; }
        public string d_memo { get; set; }
        public string belongto { get; set; }
        public Nullable<bool> d_owner { get; set; }
        public Nullable<int> bdf_id { get; set; }
        public Nullable<int> bpt_id { get; set; }
    
        public virtual BroadcastPointType BroadcastPointType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User2> User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infos> Infos { get; set; }
    }
}
