//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineVer1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POPEntities : DbContext
    {
        public POPEntities()
            : base("name=POPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BeaconDevice> BeaconDevice { get; set; }
        public virtual DbSet<BroadcastPointType> BroadcastPointType { get; set; }
        public virtual DbSet<InfoGroupp> InfoGroupp { get; set; }
        public virtual DbSet<town> town { get; set; }
        public virtual DbSet<User2> User2 { get; set; }
        public virtual DbSet<AAA> AAA { get; set; }
        public virtual DbSet<View_AspNetUsers_Infos> View_AspNetUsers_Infos { get; set; }
        public virtual DbSet<P_InfoPrice> P_InfoPrice { get; set; }
        public virtual DbSet<uv_ConditionalSearchPushAdvertisin> uv_ConditionalSearchPushAdvertisin { get; set; }
        public virtual DbSet<uv_AllBroadcast> uv_AllBroadcast { get; set; }
        public virtual DbSet<BeaconDeviceFlow> BeaconDeviceFlow { get; set; }
        public virtual DbSet<InvoiceType> InvoiceType { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<uv_PublishedInquire> uv_PublishedInquire { get; set; }
        public virtual DbSet<Infos> Infos { get; set; }
        public virtual DbSet<uv_AdvertisingCategoryCount> uv_AdvertisingCategoryCount { get; set; }
        public virtual DbSet<uv_ClassifiedAdsSearch> uv_ClassifiedAdsSearch { get; set; }
        public virtual DbSet<OrderRecord> OrderRecord { get; set; }
    
        public virtual ObjectResult<usp_PushAdvertisingStatistics_Result> usp_PushAdvertisingStatistics(Nullable<bool> getAllData, string countyCity, string townshipCity, string bdfBroadcastPoint, string dName, Nullable<System.DateTime> nowDatetime)
        {
            var getAllDataParameter = getAllData.HasValue ?
                new ObjectParameter("GetAllData", getAllData) :
                new ObjectParameter("GetAllData", typeof(bool));
    
            var countyCityParameter = countyCity != null ?
                new ObjectParameter("CountyCity", countyCity) :
                new ObjectParameter("CountyCity", typeof(string));
    
            var townshipCityParameter = townshipCity != null ?
                new ObjectParameter("TownshipCity", townshipCity) :
                new ObjectParameter("TownshipCity", typeof(string));
    
            var bdfBroadcastPointParameter = bdfBroadcastPoint != null ?
                new ObjectParameter("BdfBroadcastPoint", bdfBroadcastPoint) :
                new ObjectParameter("BdfBroadcastPoint", typeof(string));
    
            var dNameParameter = dName != null ?
                new ObjectParameter("DName", dName) :
                new ObjectParameter("DName", typeof(string));
    
            var nowDatetimeParameter = nowDatetime.HasValue ?
                new ObjectParameter("NowDatetime", nowDatetime) :
                new ObjectParameter("NowDatetime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PushAdvertisingStatistics_Result>("usp_PushAdvertisingStatistics", getAllDataParameter, countyCityParameter, townshipCityParameter, bdfBroadcastPointParameter, dNameParameter, nowDatetimeParameter);
        }
    }
}
