//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int s_id { get; set; }
        public System.DateTime s_day { get; set; }
        public System.DateTime i_day { get; set; }
        public System.DateTime i_expired_day { get; set; }
        public int bill { get; set; }
        public int ip_discount { get; set; }
        public string i_name { get; set; }
        public string i_content { get; set; }
        public int ip_days { get; set; }
        public string u_name { get; set; }
        public string u_mail { get; set; }
        public string u_phone { get; set; }
        public int u_id { get; set; }
        public int belongto { get; set; }
        public bool ifout { get; set; }
        public string invoice_code { get; set; }
    }
}
