//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User2()
        {
            this.Infos = new HashSet<Infos>();
            this.BeaconDevice = new HashSet<BeaconDevice>();
        }
    
        public string Id { get; set; }
        public string u_name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public System.DateTime HireDate { get; set; }
        public bool CurrentFlag { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string receipt { get; set; }
        public int p_fee { get; set; }
        public System.DateTime p_lastFeeDate { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string u_memo { get; set; }
        public string RoleId { get; set; }
        public bool u_active { get; set; }
        public string belongto { get; set; }
        public string CommCircleName { get; set; }
        public string u_location1 { get; set; }
        public string u_location2 { get; set; }
        public string u_location3 { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> AddressTypedId { get; set; }
        public string PostalCode { get; set; }
        public System.Data.Entity.Spatial.DbGeography SpatialLocation { get; set; }
        public int applyupgrade { get; set; }
        public string rejectreason { get; set; }
        public string u_occupation1 { get; set; }
        public string u_occupation2 { get; set; }
        public string u_occupation3 { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infos> Infos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeaconDevice> BeaconDevice { get; set; }
    }
}
