//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uv_ClassifiedAdsSearch
    {
        public int i_id { get; set; }
        public string i_name { get; set; }
        public string i_content { get; set; }
        public System.DateTime i_initial_day { get; set; }
        public System.DateTime i_expired_day { get; set; }
        public string i_location1 { get; set; }
        public string i_location2 { get; set; }
        public string i_pic1 { get; set; }
        public string i_pic2 { get; set; }
        public string i_pic3 { get; set; }
        public string i_pic4 { get; set; }
        public string i_pic5 { get; set; }
        public string i_URL { get; set; }
        public int ig_id { get; set; }
        public string u_id { get; set; }
        public bool i_unconfirm { get; set; }
        public int ip_discount { get; set; }
        public int ip_days { get; set; }
        public int bill { get; set; }
        public string i_LINE { get; set; }
        public bool i_open { get; set; }
        public string or_number { get; set; }
        public Nullable<System.DateTime> i_create_datetime { get; set; }
        public string i_probation { get; set; }
        public string i_formal_period { get; set; }
        public string ig_name { get; set; }
        public string ig_pic { get; set; }
        public Nullable<int> ig_price { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string U2_id { get; set; }
        public Nullable<int> free_id { get; set; }
        public string co_name { get; set; }
        public string co_belong { get; set; }
        public string co_location1 { get; set; }
        public string co_location2 { get; set; }
        public string co_location3 { get; set; }
        public string co_location4 { get; set; }
        public string cl_name { get; set; }
        public string cl_belong { get; set; }
        public string cl_location1 { get; set; }
        public string cl_location2 { get; set; }
        public string cl_location3 { get; set; }
        public string cl_location4 { get; set; }
        public string ac_zipcode { get; set; }
        public string ac_name { get; set; }
        public string ac_location1 { get; set; }
        public string ac_location2 { get; set; }
        public string ac_location3 { get; set; }
        public Nullable<int> ac_belong { get; set; }
        public Nullable<int> ac_family { get; set; }
        public Nullable<int> ac_building { get; set; }
    }
}
